version: '3.9'
services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - '3001:3001'
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bank-system
    ports:
      - '5433:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
